### ISSUE TITLE
action !dig

### ISSUE THREAD

**Issue by EnzoDiazDev** [newlands-quest/game#3]
`!dig` representa una acción de extraer recursos. Otras acciones similares podrían ser `!chop`, `!farm`, etc.

event payload: 
```ts
{
  message: "!dig",
  actor: id,
  timestamp: number
}
```

- [ ] Traer información del usuario de la base de datos.
- - [ ] En caso de error, notificar que el usuario no existe. 
- [ ] Comprobar que el usuario es capaz de realizar la acción.
- - [ ] En caso de no ser posible, notificar que no tiene permiso para realizar esa acción.
- [ ] Calcular con un 33% de probabilidad de éxito si ha encontrado un elemento.
- - [ ] En caso de "no encontrar nada", notificar que no tuvo éxito en la búsqueda. 
- [ ] Generar un nuevo item aleatorio.
- [ ] Responder al jugador notificando que encontró un item (y el nombre del item).
- [ ] Actualizar el inventario del usuario en la base de datos con el nuevo item.

response payload:
```ts
{
  message: "You find a table",
  timestamp: number
}
```

**Comment by EnzoDiazDev** [comment]
deprecated
