### ISSUE TITLE
query ?me

### ISSUE THREAD

**Issue by EnzoDiazDev** [newlands-quest/game#4]
`?me` es un alias de `?@self`, permite conocer información sobre sí mismo. (`self` es el nombre del usuario que realiza la acción)

event payload:
```js
{
  message: "?me",
  actor: id,
  timestamp: number
}
```

- [ ] Traer información del usuario de la base de datos.
 - - [ ] En caso de error, notificar que el usuario no existe.
 - [ ] Parsear la data en formato string. 
 - [ ] Responder al jugador.

response payload:
```js
{
  message: "Name: John\nAlive: yes\nBalance: 1536\n...",
  timestamp: number
}
```

**Comment by EnzoDiazDev** [comment]
deprecated
