### ISSUE TITLE
query ?here

### ISSUE THREAD

**Issue by EnzoDiazDev** [newlands-quest/game#5]
`?here` permite conocer información de la casilla donde el usuario se encuentra.

event payload
```js
{
  message: "?here",
  actor: id,
  timestamp: number
}
```

 - [ ] Traer información del usuario de la base de datos.
 -  - [ ] En caso de error, notificar que el usuario no existe.
 - [ ] Traer información de la casilla donde se encuentra el jugador. (El jugador siempre estará en una casilla)
 - [ ] Parsear la data de la casilla en formato string. 
 - [ ] Responder al jugador con la información de la casilla. 

```js
{
  response: "You are in an empty area, but the soil is very fertile here.",
  timestamp: number
}
```

**Comment by EnzoDiazDev** [comment]
deprecated
